name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Build
        run: flyctl deploy --remote-only --build-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy
        run: flyctl deploy --remote-only
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
